---
# SPDX-FileCopyrightText: 2025 The UniversalLoader development team
#
# SPDX-License-Identifier: CC0-1.0
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
